### ISSUE TITLE
Can you make the tree to up down mode

### ISSUE THREAD

**Issue by sunjianchun** [Yakubovich/descendant_tree#3]
Hi man, Can you make the tree to up down mode, thanks?
![image](https://user-images.githubusercontent.com/20220710/32411170-42509bfc-c1a2-11e7-9271-edf5d4d654ad.png)

**Comment by Yakubovich** [comment]
Hi,

I actually started implementing a vertical mode (you can turn it on in the
code by changing line #40 of scripts/tree.js to var vertical = true;

However, it doesn't work very well and the labels overlap. Unfortunately
it's turning into quite a bit of work so I won't be able to do it soon.

**Comment by sunjianchun** [comment]
@Yakubovich Thank you very much,  which is the best I could found. When i modify the tree.js  by what you say , the browser (Chrom) can not render. But now it's enough for me.
